environment:
  NuGetApiKey:
    secure: +0k/7Pu/LMQofUKv3ZjNeV8kMqZBkNSRlpUVx3IWgr6EfA0O0ELe3XZAj0Pe8LPk

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

skip_commits:
  message: /updated readme.*|update readme.*|updating readme.*s/

build: false

test-script:
  - ps: . .\Build.ps1